version: '3.1'
services:

  mysql-server:
    image: mysql:8.4.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis-server:
    image: redis:7.2.4
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq-server:
    image: rabbitmq:3.13.2-management
    container_name: 'rabbitmq'
    ports:
    - "5672:5672"
    - "15672:15672"
    volumes:
      - rabbit_mq_lib_volume:/var/lib/rabbitmq
      - rabbit_mq_log_volume:/var/log/rabbitmq

volumes:
  mysql_data:
    driver: local
  redis_data:
  rabbit_mq_lib_volume:
  rabbit_mq_log_volume: